# Generated by Django 3.0.8 on 2020-08-04 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('year_founded', models.SmallIntegerField(blank=True, null=True)),
                ('team_size', models.SmallIntegerField(blank=True, null=True)),
                ('original_pull', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('funding', models.CharField(blank=True, max_length=20, null=True)),
                ('relevant', models.BooleanField(blank=True, null=True)),
                ('dead', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('name', models.CharField(default='NONAME', max_length=50, primary_key=True, serialize=False)),
                ('website', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('name', models.CharField(default='NONAME', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(default='NONAME', max_length=50, primary_key=True, serialize=False)),
                ('companies', models.ManyToManyField(to='data.Company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='investors',
            field=models.ManyToManyField(to='data.Investor'),
        ),
        migrations.AddField(
            model_name='company',
            name='verticals',
            field=models.ManyToManyField(blank=True, null=True, to='data.Vertical'),
        ),
    ]
